search_space: nasbench201

benchmark:
  name: custom  # We will register this manually

search:
  name: regularized_evolution
  seed: 42
  population_size: 50
  sample_size: 10
  mutation_rate: 1.0
  max_evaluations: 100
  epochs: 10
  checkpoint_freq: 1000_000

save: /mnt/c/Users/Luis/Documents/Uni-DESKTOP-F7N3QC8/TU Dresden/4. Semester/CC-Seminar/hwnas/test
data: ../dataset
batch_size : 32
dataset: cifar10
train_portion: 10

logging:
  log_frequency: 1
  log_output_dir: logs/
  save_model: false
